# Generated by Django 4.0.5 on 2022-06-09 18:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='real name')),
                ('surname', models.CharField(max_length=200, verbose_name='last name')),
                ('email', models.EmailField(max_length=200, verbose_name='e-mail address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('validated_email', models.BooleanField(default=False)),
                ('validatet_phone', models.BooleanField(default=False)),
            ],
        ),
    ]
