# Generated by Django 4.0.5 on 2022-06-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='validatet_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='validated_phone',
            field=models.BooleanField(default=False, verbose_name='validated phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='validated_email',
            field=models.BooleanField(default=False, verbose_name='validated e-mail'),
        ),
    ]
